name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: rsync
      shell: bash
      env:
        SSH_KEY: ${{ secrets.UMBRA_DEV_EC2 }}
      run: echo "$SSH_KEY" > ssh.key && chmod 600 ssh.key && rsync -e 'ssh -i ssh.key -o StrictHostKeyChecking=no' --recursive --compress --progress build/ ubuntu@ludos.dev:/var/www/umbra-dev/
      # run: echo "$SSH_KEY" > ssh.key && chmod 600 ssh.key && scp -i ssh.key -o StrictHostKeyChecking=no' -rC build/ ubuntu@ludos.dev:/var/www/umbra-dev/
    - run: rm ssh.key