name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: nearwood/umbra-server
        tag_with_ref: true
# deploy:
#   environment: dev
#   env:
#     AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
#     ECR_REPOSITORY: MY_ECR_REPOSITORY           # set this to your Amazon ECR repository name
#     ECS_SERVICE: umbra-dev                 # set this to your Amazon ECS service name
#     ECS_CLUSTER: umbra-dev                 # set this to your Amazon ECS cluster name
#     ECS_TASK_DEFINITION: MY_ECS_TASK_DEFINITION # set this to the path to your Amazon ECS task definition
#     CONTAINER_NAME: 
