# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
    - run: npm run build
    # - name: Upload Build Artifact
    #   uses: actions/upload-artifact@v2.2.2
    #   with:
    #     name: umbra
    #     path: build/
    #     if-no-files-found: error
    #     retention-days: 1
    - name: Rsync with server
      env:
        SSH_KEY: ${{ secrets.UMBRA_DEV_EC2 }}
      run: echo $SSH_KEY > ssh.key && chmod 600 ssh.key && ls -la ssh.key && rsync -e 'ssh -v -i ssh.key' -aznvP build/ ubuntu@ludos.dev:/var/www/umbra-dev/
    - run: rm ssh.key